//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfluenceAutomator {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class JSON {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal JSON() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConfluenceAutomator.JSON", typeof(JSON).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;type&quot;:&quot;page&quot;,&quot;title&quot;:&quot;new page&quot;,&quot;space&quot;:{&quot;key&quot;:&quot;RAID2&quot;},&quot;body&quot;:{&quot;storage&quot;:{&quot;value&quot;:&quot;&lt;p&gt;This is a new page&lt;/p&gt;&quot;,&quot;representation&quot;:&quot;storage&quot;}}}.
        /// </summary>
        internal static string Basic {
            get {
                return ResourceManager.GetString("Basic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;id&quot;: &quot;1234&quot;,
        ///    &quot;type&quot;: &quot;page&quot;,
        ///    &quot;title&quot;: &quot;Example Content title&quot;,
        ///    &quot;space&quot;: {
        ///        &quot;id&quot;: 11,
        ///        &quot;key&quot;: &quot;RAID2&quot;,
        ///        &quot;name&quot;: &quot;Example space&quot;,
        ///        &quot;description&quot;: {
        ///            &quot;plain&quot;: {
        ///                &quot;value&quot;: &quot;This is an example space&quot;,
        ///                &quot;representation&quot;: &quot;plain&quot;
        ///            }
        ///        },
        ///        &quot;_links&quot;: {
        ///            &quot;self&quot;: &quot;http://myhost:8080/confluence/rest/api/space/TST&quot;
        ///        }
        ///    },
        ///    &quot;version&quot;: {
        ///        &quot;by&quot;: {
        ///            &quot;ty [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string payload2 {
            get {
                return ResourceManager.GetString("payload2", resourceCulture);
            }
        }
    }
}
